// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Nodefs from "node:fs";
import * as Js_string from "rescript/lib/es6/js_string.js";

Zora.test("Fs", (async function (t) {
        t.test("readFile should read entire file", (async function (t) {
                var fh = await Nodefs.promises.open(__filename, "r");
                var buffer = await fh.readFile();
                await fh.close();
                t.ok(buffer.indexOf("Random string: Gh2e71pdHhPxU") > 1, "buffer index was not greater than zero");
              }));
        t.test("readFileWith should read entire file as a string", (async function (t) {
                var fh = await Nodefs.promises.open(__filename, "r");
                var buffer = await fh.readFile({
                      encoding: "UTF-8"
                    });
                await fh.close();
                t.ok(Js_string.indexOf("Random string: uCF6c5f3Arrq", buffer) > 0, "buffer string indexOf was not greater than zero");
              }));
      }));

export {
  
}
/*  Not a pure module */
