// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Zora from "zora";

Zora.test("Path", (function (t) {
        t.test("basename should isolate filename with extension", (function (t) {
                t.equal(Path.posix.basename("/tmp/myfile.html"), "myfile.html", "");
              }));
      }));

export {
  
}
/*  Not a pure module */
