// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Promises from "node:timers/promises";

Zora.test("Timers (promises)", (async function (t) {
        t.test("setTimeout", (async function (t) {
                await Promises.setTimeout(100);
                t.ok(true, "");
              }));
        t.test("setImmediate", (async function (t) {
                var yes = await Promises.setImmediate("yes");
                t.equal(yes, "yes", "");
              }));
      }));

export {
  
}
/*  Not a pure module */
