// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EventEmitter$NodeJs from "../../src/EventEmitter.res.js";

EventEmitter$NodeJs.Make({});

var uniqueSymbol = (Symbol("emitter1"));

var Events = {
  symbol: uniqueSymbol,
  text: "text",
  integer: "integer",
  textAndInteger: "textAndInteger"
};

var Emitter1 = {
  uniqueSymbol: uniqueSymbol,
  Events: Events
};

export {
  Emitter1 ,
}
/*  Not a pure module */
