// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Nodestream from "node:stream";

function makeReadableEmpty() {
  return new Nodestream.Readable({
              objectMode: false,
              autoDestroy: true,
              destroy: (function (error, callback) {
                  callback((error == null) ? undefined : Caml_option.some(error));
                }),
              read: (function (param) {
                  
                })
            });
}

function makeWritableEmpty() {
  return new Nodestream.Writable({
              objectMode: false,
              autoDestroy: true,
              destroy: (function (error, callback) {
                  callback((error == null) ? undefined : Caml_option.some(error));
                }),
              write: (function (param, param$1, callback) {
                  callback(undefined);
                })
            });
}

export {
  makeReadableEmpty ,
  makeWritableEmpty ,
}
/* node:stream Not a pure module */
