// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tls$NodeJs from "./Tls.res.js";

var Events = {};

var Impl = {};

var HttpsServer = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Agent = {
  Events: Events$1
};

export {
  HttpsServer ,
  Agent ,
}
/* Tls-NodeJs Not a pure module */
