// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Net$NodeJs from "./Net.res.js";

var Events = {};

var Impl = {};

var TlsSocket = {
  Events: Events,
  Impl: Impl
};

var Events$1 = {};

var Impl$1 = {};

var TlsServer = {
  Events: Events$1,
  Impl: Impl$1
};

export {
  TlsSocket ,
  TlsServer ,
}
/* Net-NodeJs Not a pure module */
