// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";

var p = {
  root: "/",
  name: "file",
  ext: ".txt"
};

console.log(Path.format(p));

export {
  p ,
}
/*  Not a pure module */
