// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "process";
import * as Nodereadline from "node:readline";

Nodereadline.clearLine(Process.stdout, 1, (function () {
        console.log("line cleared");
      }));

Nodereadline.clearScreenDown(Process.stdout, (function () {
        console.log("screen cleared");
      }));

Nodereadline.cursorTo(Process.stdout, 1, 2, (function () {
        console.log("cursor to");
      }));

Nodereadline.moveCursor(Process.stdout, 1, 2, (function () {
        console.log("cursor moved");
      }));

export {
  
}
/*  Not a pure module */
